Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MyIAMReadOnlyPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:List*
                  - iam:Get*
                  - iam:GenerateCredentialReport,
                  - iam:GenerateServiceLastAccessedDetails",
                  - iam:SimulateCustomPolicy,
                  - iam:SimulatePrincipalPolicy
                Resource: "*"
# aws cloudformation validate-template --template-body file://IAM_ROLE_3.1.1.yaml
# aws cloudformation create-change-set --stack-name myrole101 --change-set-name first-change-set101 --change-set-type CREATE --template-body file://IAM_ROLE_3.1.1.yaml
# aws cloudformation create-stack --stack-name myrole101 --template-body file://IAM_ROLE_3.1.1.yaml --capabilities CAPABILITY_NAMED_IAM


#list roles - aws iam list-roles
#get role - aws iam get-role --role-name MyRole
